name: Test documentation

on:
  pull_request:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.10.1
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements_dev.txt
          pip install .
          sudo apt install pandoc
      - name: Test documentation
        run: |
          cd docs
          make html
